creation_rules:
  # Kubernetes deployments with secrets in a `**/secrets` dir.
  - path_regex: '.*secrets.*\.(yaml|yml|json)$'
    # Encrypt only sensitive fields.
    encrypted_regex: "^(data|stringData)$"
    age: age15zhjt0ckkpckkk4f8wy3glh9cahdd68v3mr73p32z8mga7s3e5usx2sn6m

  # # Talos machine configs
  # - path_regex: '^talos/.*\.(yaml|yml)$'
  #   encrypted_regex: "^(secrets|token|ca|crt|key|password)$"
  #   age:
  #     - age15zhjt0ckkpckkk4f8wy3glh9cahdd68v3mr73p32z8mga7s3e5usx2sn6m
