creation_rules:
  # Kubernetes secrets in a **/secrets/** directory
  - path_regex: '.*secrets.*\.(yaml|yml|json)$'
    encrypted_regex: "^(data|stringData)$"
    age: age15zhjt0ckkpckkk4f8wy3glh9cahdd68v3mr73p32z8mga7s3e5usx2sn6m
