---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync-backup-wallabag-images
spec:
  # The PVC to be backed up
  sourcePVC: wallabag-claim-images
  trigger:
    # Take a backup every day at 3am
    schedule: "0 3 * * *"
  restic:
    # Prune the repository (repack to free space) every 2 weeks
    pruneIntervalDays: 14
    # Name of the Secret with the connection information
    repository: volsync-config-wallabag-images
    # Retention policy for backups
    retain:
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    # Clone the source volume prior to taking a backup to ensure a
    # point-in-time image.
    copyMethod: Clone
    # The StorageClass to use when creating the PiT copy (same as source PVC if omitted)
    #storageClassName: my-sc-name
    # The VSC to use if the copy method is Snapshot (default if omitted)
    #volumeSnapshotClassName: my-vsc-name
