apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: wallabag
  name: wallabag-claim-images
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
