apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: ihatemoney
  name: ihatemoney-claim
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
