apiVersion: v1
kind: Secret
metadata:
    name: wallabag-secrets
    namespace: wallabag
    labels:
        service: wallabag
type: Opaque
stringData:
    symfony-env-secret: ENC[AES256_GCM,data:xctvNhX/TvzSxCzHZW4zdgCwv5hXLFkLjwnGIZXlFG791dnScci4+dgECp6nVraGb2U=,iv:yVIUN3pKqSJCcnkGHrdWDym0lrstGwRKBQRdS4RdCS8=,tag:lPCPm+LjG7H1EhIB9tnJQg==,type:str]
sops:
    age:
        - recipient: age15zhjt0ckkpckkk4f8wy3glh9cahdd68v3mr73p32z8mga7s3e5usx2sn6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcVBHNnV6ME52elhFUGd4
            VmxkbVhzcGg2M1VSVk91d0NXOWtmN3M3dURFCnI0V1dJQnh1L200S1FXYm82aUIr
            L2pmZ0JrcXBLcTlaUkJjUVVxWmQ5RkEKLS0tIFVFK1B0d0lGZHFaa0lRS3lLWVU5
            eVRDQjFmNFl0dmxPNFhLb2FjaVRBRUUKojXKM7XJA0JoZfLSb4erkrpDAQ7g/CFh
            00fm3fRfDNKnM0sEEYcqwIrd98tpJfwKiBGQjjTqYCw13jvIXTki2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T18:06:21Z"
    mac: ENC[AES256_GCM,data:StLiZjH53La4yObjSlDvOmkVe/dhc7DLzQ1i61hcfNNEh2VZPeiekXIVHP6g/yEnrWNdDD5necC8IipUte2iPbrVqLu3W0v36X0dT84qLaZhyOnvimL6R9U105N+AFbrwt0VJr5CO/hqc+jOvRIVVITPcTjgE+fCYa18sthHfpg=,iv:Pi8AyHN3oEDiSmEE6PHiXJpy+dSlKbRr1hJb4ny42RY=,tag:8sw5jYYCglAp0gxcFkVaeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
