apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: jellyfin
  name: jellyfin-claim-config
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
