apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: jellyfin
  name: jellyfin-claim-cache
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
