apiVersion: v1
data:
  SYMFONY__ENV__DOMAIN_NAME: http://localhost
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 44c765d35191d22e90565a71aa27828a52d1b5d3
    katenary.v3/version: master
  labels:
    {{- include "downloads.labels" . | nindent 4 }}
    katenary.v3/component: wallabag
  name: '{{ include "downloads.fullname" . }}-wallabag'
