# Tailscale Secrets for the reverse proxy instance.
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:iOotHqXpDwCuqBsOifW2hvMFfV7Hrgbdz6kF3s7ekN6TCgvvD9ggp/WY8qHlXzV6SP9mhEkspLGs/27keQk=,iv:vFksk0KXDjka4qYOC8vQjwjDQ0GRonJKAznn/1x19fM=,tag:j0PqD/h/uM2z0xy4dEhzDQ==,type:str]
sops:
    age:
        - recipient: age15zhjt0ckkpckkk4f8wy3glh9cahdd68v3mr73p32z8mga7s3e5usx2sn6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTk56T1VhOXQ1bFI4OSt5
            aUJwYWJkTXM4ZHNsSVBWSGdJNFRMa3VNYUNJCjQyM0NDZ1BHb0dhak5RSkZQUEdu
            Q0d3eXBpUE1CQnN2Y1krUDhaZWFOZ3cKLS0tIG1uUld0STd4MTVsVnVNcHd2ZWZq
            dGZ4eGQzWWpVK1RaaWtBbXpya3V5Y3cKc54pDQNg3s7qXAsYskJefl0eN/H1BYzD
            SSXX14UfsfLXOcKaLElvClmgCJjyH3o9oWZ7aC1AwLx0ZRu3zpUsyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T19:44:51Z"
    mac: ENC[AES256_GCM,data:a8TJurUR8Hd+bCz0sbX7vh+f6GUz7RvzWKne6yOXdVDbbnxEd3GukbGsRSXP2UWwVHN5+bbxOOiSpoIjcRI1/wthlp9Obj0kM2e0AYNMId4lB7JAKxCFsrkgmPLCHTbmUuznH3ndN+l7l5NqdU36K8xtu627ZVMoVB2DBR6B/LQ=,iv:IMuYhYyHIanOfG7l5CX6tr4yHmPKFcGPG05g9GqBeCE=,tag:HO8PNqv1x5LBCeVtpIqrmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
