# Tailscale Secrets for the dns instance.
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth-dns
    namespace: tailscale
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:mUUiSY2Tpn0KZk2ZGWzw/dVNlKZZ/14zMagzyepgRjDwZZdzi7QaoDKuc+hP8yLiT/uzFDCuLAyNzgtzrQ==,iv:D6a1fcw0XlUvYZyn/JeTeK9Y6KSN8fge/fpgcj0+HxQ=,tag:EFAhlCidp+/+xzVcoyyVSg==,type:str]
sops:
    age:
        - recipient: age15zhjt0ckkpckkk4f8wy3glh9cahdd68v3mr73p32z8mga7s3e5usx2sn6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WkRkWGZEYThmbVlBbVhY
            YzRHMkd3Vk50ZVdqeDE3Zk54QVBnS2UzZ1E4CjB5UFEzem5zTERQcVRic2tNS1Nl
            bVg4VUNzQ0ltSHhoTklNZVpVMEpXWDQKLS0tIFIzTS91VUV2T20wQXovdnlhZy9a
            c2lZMzZkYTE3MlZMRm5lMkxlMkVKZFkK7wzuvYtNwQRYIG2hoBTpOKASdGBbkARl
            ncblD05GtYO0I/zSISNjEwTvX4LVQ/nhEeHqMu8PwoFaiqhyB5reFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T19:43:13Z"
    mac: ENC[AES256_GCM,data:X5aVOyg2s+h+9cdmVJByo7GbqDMZKl39P4nWvN4yDEjWX/+qG/YvDs1+Qc/Ak+Cg9xy4Tojw2yQ7p7XEX8kSX5HH1rOwQPKSJNIDh6D3oKfipJK6btdvoLnrM/Sb+9rf2jstp/fZrsL3VbA2oNBnE5cgOljwZ+N8G8oWSmRUDB8=,iv:ZwJw8dse3kMNByP0Hgtr/mguSSaVEti+5V/NIFFxPLs=,tag:Bz/E+Qof14bz3p9Cnsyp5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
