apiVersion: v1
kind: Pod
metadata:
  name: tailscale-reverse-proxy
  namespace: tailscale
spec:
  serviceAccountName: tailscale
  restartPolicy: Always
  initContainers:
    - name: sysctler
      image: busybox:latest
      securityContext:
        privileged: true
      command: ["/bin/sh"]
      args:
        - -c
        - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
  containers:
    - name: tailscale
      image: ghcr.io/tailscale/tailscale:v1.92.4
      env:
        - name: TS_KUBE_SECRET
          value: tailscale-auth
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_USERSPACE
          value: "false"
        - name: TS_DEST_IP
          # Set to cluster IP of traefik
          value: 10.100.200.166
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
