# This secret is required for VolSync's restic syncing.
#
# https://volsync.readthedocs.io/en/stable/usage/restic/index.html
apiVersion: v1
kind: Secret
metadata:
    name: volsync-config-ihatemoney
    namespace: apps
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2uERPMwhVo96/VxLRo3AlW/0yw==,iv:F3GjiYecsnHue4NiYRyxkGEP7MvOsv1y+z5Dm38hXOQ=,tag:Pvq6Q4U85Czz/tA7EQosMw==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Oh2+/2hQRCruXCJQkri8Y2PZrupuuT7dO67KMnLzFZpqHPifqRrSPv/nehv3lvkGaXDLynI9P28BDrGsvMeR/VP0vlIriOOEgKXgVJIOGsV7lOJ9BQ5M0CiXAOjeSA==,iv:xKE+M8IHGqol4zkN2mHUXjpmwnuO5veHq0CKA42Uiaw=,tag:wTcpiigGnOYb3UfopfW2yw==,type:str]
    #ENC[AES256_GCM,data:ehkYf1pdIT+tW9PDLUiJTvvDJN1bh8d50iKJqAoj,iv:5V/8VPtgfy4IpFRbEExsoRoIjjP+jB3yqwEFQ+fDfA4=,tag:0+SZAKHGSuQLYkpFwNzDbA==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:w6en/1fiyiq+HiprX6M5NeSzHYvVqI6lcGTmp0oc38qslRyNWQjUvkkry/NkUdD8a7A=,iv:2FUaWF1uRuY7p1H7+v8f+Bovw939VBEaCebWL3CzE8Q=,tag:shPeydbskF/y1OshpqFaDA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:L0ZwJETb1i74OjvXIb2R8GfB8/WqCKtM9UgpZR5jHOk=,iv:WPlAaMW1blf0isjPZl4p05biFdvQLCqs9w3ZMwRZsRQ=,tag:Uv85d1w2By5axtWtPGOTTA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OIzJUGbmfNS3sRPRcfyHFRrEUWQYrlD1LRFUnkAbnRnL50XNxM7YUDZaeDSV8uWMSzQzYHX8A6sbtpsXrdg8GA==,iv:Rm9mR8d+i6awAwH/EzNmeFnSiGNAA7/39VQK6f2GdQY=,tag:Ceej4lfgzRtE0JXRwcU07A==,type:str]
sops:
    age:
        - recipient: age15zhjt0ckkpckkk4f8wy3glh9cahdd68v3mr73p32z8mga7s3e5usx2sn6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreFZHS3A4Z21qOGF6WlRS
            MGdBbUU2aWM1eXRGUlZubk9sMU16bWxnUDEwCjJQek9nVzNOeDZ4Y0JDV2g4UjRy
            MkgwbnZHbzVPb0wwbzRWNkRFa0ZzekEKLS0tIGhub0t2QUNsVHZ1ZzEyUmJRc3dX
            U0JJMWVLVFRGc2hXQW0rT2ZBVk1GS2sKh0pE/RE/N3Q4VPYLQIhPH4wcc6tolmZX
            ukkylNFxaSAy/HN/324R1m2EpmB7gfT3Q0Oao2IeCKGh3oB3BIi92g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T19:25:11Z"
    mac: ENC[AES256_GCM,data:nqZvs+skg+2PLegvgsCfRdz2kqXi1MxmJwqTXRsik+RpmdkesdgAku48KrRcbdkJWc2VYEtO9r8nIZmDHgA1l9ZFPUpzr1+DQjlNHnUdhqJhgYW+xRQ2NZ4B8+l9lOiX24kMEA0vSDXpLjRN7XlCCDMpIXF+2+rjBqkcCoF0Jys=,iv:WPzVr+mCyCikMjw0bLvBLg4dxTXlfAlq50ya7pD79jM=,tag:DzHBi/Rg0r5dvDHPCwropA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
